name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build docker --tag olfi01/metalpyports
    - name: Push the Docker image
      if: ${{ github.event_name == 'push' }}
      run: docker push olfi01/metalpyports
